Rails.application.config.assets.precompile += %w( hosts.css )
Rails.application.config.assets.precompile += %w( hosts.js )
Rails.application.config.assets.precompile += %w( angular/app.js )
Rails.application.config.assets.precompile += %w( angular/config.js )
Rails.application.config.assets.precompile += %w( angular/translations.js )
Rails.application.config.assets.precompile += %w( angular/directives.js )
Rails.application.config.assets.precompile += %w( angular/controllers.js )