production:
  adapter: postgresql
  encoding: <%= ENV["PRODUCTION_UNICODE"] %>
  database: <%= ENV["PRODUCTION_DATABASE"] %>
  username: <%= ENV["PRODUCTION_USERNAME"] %>
  password: <%= ENV["PRODUCTION_PASSWORD"] %>
  host: <%= ENV["PRODUCTION_HOST"] %>
  port: <%= ENV["PRODUCTION_POST"] %>

development:
  adapter: sqlite3
  pool: 5
  timeout: 5000
  database: db/test.sqlite3

test:
  adapter: sqlite3
  pool: 5
  timeout: 5000
  database: db/test.sqlite3
