default: &default
  adapter: postgresql
  encoding: unicode
  username: vagrant
  password: vagrant
  pool: 5

development:
  <<: *default
  database: bazicon_development

test:
  <<: *default
  database: bazicon_test

production:
  <<: *default
  database: bazicon_production
  username: bazicon
  password: <%= ENV['BAZICON_DATABASE_PASSWORD'] %>
