class OutgoingExchangeController < ApplicationController

  # GET /ogx/dash
  # POST /ogx/dash?lc=INTEGER
  def dash
    @committes = ExpaOfficeDAO.list_lcs_by_user_xp_id(session[:expa_id])
    if params.include?('lc')
      prepare_information_list(params['lc'].to_i)
    else
      prepare_information_list(@committes.first.xp_id)
    end
  end

  # GET /ogx/list
  # POST /ogx/list?lc=INTEGER&page=INTEGER&date_start=STRING&date_end=STRING
  def list
    prepare_expansor_expansions
    if params.include?('lc')
      lc_info_query = @expansor_expansions[params['lc']][1]
      if @user.list_programs == ExpaPerson.roles[:role_mc]
        lc_list_query = @expansor_expansions[params['lc']][1]
      elsif @user.xp_home_lc_id == @expansor_expansions[params['lc']][1]
        lc_list_query = @expansor_expansions[params['lc']][1]
      else
        lc_list_query = @expansor_expansions[0][1]
      end
    else
      lc_info_query = @expansor_expansions[0][1]
      lc_list_query = @expansor_expansions[0][1]
    end
    if params.include?('lc')
      page = params['page']
    else
      page = 0
    end
    if params.include?('date_start') && params.include?('date_end')
      date_start = DateTime.strptime(params['date_start'], '%d-%m-%y').to_time
      date_end = DateTime.strptime(params['date_end'], '%d-%m-%y').to_time
    else
      date_start = Time.new(Time.new.year, Time.new.month, 1)
      date_end = Time.new
    end

    @people = filter_list_leads(lc_list_query,page, date_start, date_end)
  end

  # GET /ogx/detail?id=INTEGER
  def detail
    return redirect_to main_path unless params.include?('id')

    EXPAHelper.auth(ENV['ROBOZINHO_EMAIL'],ENV['ROBOZINHO_PASSWORD'])
    @person = ExpaPerson.find_by_xp_id(params['id'].to_i)
    if @person.nil?
      return redirect_to main_path
    else
      begin
        @person.update_from_expa(EXPA::People.find_by_id(params['id']))
        @person.save
      rescue => exception
        puts exception
        return redirect_to main_path
      end
    end

    generate_program_product_array
    prepare_custom_fields(@person)
  end

  private

  def generate_program_product_array
    programs = DigitalTransformation.interested_program
    programs = programs[1,programs.size]

    gcdp = DigitalTransformation.sub_product_global_citizen
    gcdp = gcdp[1,gcdp.size]

    gip = DigitalTransformation.sub_product_global_talent
    gip = gcdp[1,gip.size]

    @program_product_array = [programs[0]].product(gcdp)+[programs[1]].product(gip)
  end

  def prepare_custom_fields(person)
    @custom_fields = {'nil' => nil}

    unless person.customized_fields.nil?
      keys = JSON.parse(person.customized_fields).keys
      keys.each do |key|
        if key == 'escolaridade' || key == 'universidade' || key == 'curso'
        elsif key == 'prevents' || key == 'difficulty'
          @custom_fields[key] = JSON.parse(person.customized_fields)[key]
        end
      end
    end
  end

  def prepare_information_list(lc)
    @info = {}

    office = ExpaOffice.find_by_xp_id(lc)

    if lc == 1606
      sql_lc_query = 'expa_people.xp_home_mc_id = ' + ExpaOffice.find_by_xp_id(lc).id.to_s
    else
      sql_lc_query = 'expa_people.entity_exchange_lc_id = ' + ExpaOffice.find_by_xp_id(lc).id.to_s
    end

    this_year_string = "'#{Time.new(Time.new.year, 1, 1).strftime('%Y-%m-%d')}' AND '#{Time.now.strftime('%Y-%m-%d')}')"
    past_year_string = "'#{Time.new(Time.new.year - 1, 1, 1).strftime('%Y-%m-%d')}' AND '#{(Time.new(Time.new.year, 1, 1) - 1).strftime('%Y-%m-%d')}')"

    this_month_string = "'#{Time.new(Time.new.year, Time.new.month, 1).strftime('%Y-%m-%d')}' AND '#{Time.now.strftime('%Y-%m-%d')}')"
    past_month_string = "'#{Time.new(Time.new.year, Time.new.month-1, 1).strftime('%Y-%m-%d')}' AND '#{(Time.new(Time.new.year, Time.new.month, 1) - 1).strftime('%Y-%m-%d')}')"
    this_month_past_year_string = "'#{Time.new(Time.new.year - 1, Time.new.month, 1).strftime('%Y-%m-%d')}' AND '#{(Time.new(Time.new.year - 1, Time.new.month + 1, 1) -1).strftime('%Y-%m-%d')}')"

    sql_gcdp = "expa_opportunities.xp_programmes LIKE '%GCDP%'"
    sql_gip = "expa_opportunities.xp_programmes LIKE '%GIP%'"
    sql_ogx = "(expa_opportunities.xp_programmes LIKE '%GCDP%' OR expa_opportunities.xp_programmes LIKE '%GIP%')"

    sql_re = "(expa_applications.xp_current_status = 4 OR expa_applications.xp_status = 4)"
    sql_ma = "(expa_applications.xp_current_status = 3 OR expa_applications.xp_status = 3)"

    @info['leads_this_month'] = ExpaPersonDAO.number_of_leads(office, Time.new(Time.new.year, Time.new.month, 1)..Time.now)
    @info['leads_past_month'] = ExpaPersonDAO.number_of_leads(office, Time.new(Time.new.year, Time.new.month-1, 1)..Time.new(Time.new.year, Time.new.month, 1) - 1)
    @info['leads_past_year'] = ExpaPersonDAO.number_of_leads(office, Time.new(Time.new.year - 1, Time.new.month, 1)..Time.new(Time.new.year - 1, Time.new.month + 1, 1) -1)

    @info['ip_ogcdp_this_month'] = ActiveRecord::Base.connection.execute("SELECT expa_people.* FROM expa_people INNER JOIN expa_applications ON expa_applications.xp_person_id = expa_people.xp_id INNER JOIN expa_opportunities ON expa_applications.xp_opportunity_id = expa_opportunities.id WHERE " + sql_lc_query + "AND (expa_people.xp_created_at BETWEEN " + this_month_string + " AND expa_people.xp_status = 1 AND " + sql_gcdp).count
    @info['ip_ogcdp_past_month'] = ActiveRecord::Base.connection.execute("SELECT expa_people.* FROM expa_people INNER JOIN expa_applications ON expa_applications.xp_person_id = expa_people.xp_id INNER JOIN expa_opportunities ON expa_applications.xp_opportunity_id = expa_opportunities.id WHERE " + sql_lc_query + "AND (expa_people.xp_created_at BETWEEN " + past_month_string + " AND expa_people.xp_status = 1 AND " + sql_gcdp).count.to_f
    @info['ip_ogcdp_past_year'] = ActiveRecord::Base.connection.execute("SELECT expa_people.* FROM expa_people INNER JOIN expa_applications ON expa_applications.xp_person_id = expa_people.xp_id INNER JOIN expa_opportunities ON expa_applications.xp_opportunity_id = expa_opportunities.id WHERE " + sql_lc_query + "AND (expa_people.xp_created_at BETWEEN " + this_month_past_year_string + " AND expa_people.xp_status = 1 AND " + sql_gcdp).count.to_f

    @info['ip_ogip_this_month'] = ActiveRecord::Base.connection.execute("SELECT expa_people.* FROM expa_people INNER JOIN expa_applications ON expa_applications.xp_person_id = expa_people.xp_id INNER JOIN expa_opportunities ON expa_applications.xp_opportunity_id = expa_opportunities.id WHERE " + sql_lc_query + "AND (expa_people.xp_created_at BETWEEN " + this_month_string + " AND expa_people.xp_status = 1 AND " + sql_gip).count
    @info['ip_ogip_past_month'] = ActiveRecord::Base.connection.execute("SELECT expa_people.* FROM expa_people INNER JOIN expa_applications ON expa_applications.xp_person_id = expa_people.xp_id INNER JOIN expa_opportunities ON expa_applications.xp_opportunity_id = expa_opportunities.id WHERE " + sql_lc_query + "AND (expa_people.xp_created_at BETWEEN " + past_month_string + " AND expa_people.xp_status = 1 AND " + sql_gip).count.to_f
    @info['ip_ogip_past_year'] = ActiveRecord::Base.connection.execute("SELECT expa_people.* FROM expa_people INNER JOIN expa_applications ON expa_applications.xp_person_id = expa_people.xp_id INNER JOIN expa_opportunities ON expa_applications.xp_opportunity_id = expa_opportunities.id WHERE " + sql_lc_query + "AND (expa_people.xp_created_at BETWEEN " + this_month_past_year_string + " AND expa_people.xp_status = 1 AND " + sql_gip).count.to_f

    @info['ma_this_month'] = ExpaApplicationDAO.number_of_ma(office, Time.new(Time.new.year, Time.new.month, 1)..Time.now)
    @info['ma_past_month'] = ExpaApplicationDAO.number_of_ma(office, Time.new(Time.new.year, Time.new.month-1, 1)..Time.new(Time.new.year, Time.new.month, 1) - 1)
    @info['ma_past_year'] = ExpaApplicationDAO.number_of_ma(office, Time.new(Time.new.year - 1, Time.new.month, 1)..Time.new(Time.new.year - 1, Time.new.month + 1, 1) -1)

    @info['re_this_month'] = ExpaApplicationDAO.number_of_re(office, Time.new(Time.new.year, Time.new.month)..Time.now)
    @info['re_past_month'] = ExpaApplicationDAO.number_of_re(office, Time.new(Time.new.year, Time.new.month-1, 1)..Time.new(Time.new.year, Time.new.month, 1) - 1)
    @info['re_past_year'] = ExpaApplicationDAO.number_of_re(office, Time.new(Time.new.year - 1, Time.new.month, 1)..Time.new(Time.new.year - 1, Time.new.month + 1, 1) -1)

    @info['ma_ogcdp_this_month'] = ActiveRecord::Base.connection.execute("SELECT expa_applications.* FROM expa_applications INNER JOIN expa_people ON expa_applications.xp_person_id = expa_people.xp_id INNER JOIN expa_opportunities ON expa_applications.xp_opportunity_id = expa_opportunities.id WHERE " + sql_lc_query + " AND (expa_applications.xp_updated_at BETWEEN " + this_month_string + " AND " + sql_ma + " AND " + sql_gcdp).count.to_f
    @info['ma_ogcdp_past_month'] = ActiveRecord::Base.connection.execute("SELECT expa_applications.* FROM expa_applications INNER JOIN expa_people ON expa_applications.xp_person_id = expa_people.xp_id INNER JOIN expa_opportunities ON expa_applications.xp_opportunity_id = expa_opportunities.id WHERE " + sql_lc_query + " AND (expa_applications.xp_updated_at BETWEEN " + past_month_string + " AND " + sql_ma + " AND " + sql_gcdp).count.to_f
    @info['ma_ogcdp_past_year'] = ActiveRecord::Base.connection.execute("SELECT expa_applications.* FROM expa_applications INNER JOIN expa_people ON expa_applications.xp_person_id = expa_people.xp_id INNER JOIN expa_opportunities ON expa_applications.xp_opportunity_id = expa_opportunities.id WHERE " + sql_lc_query + " AND (expa_applications.xp_updated_at BETWEEN " + this_month_past_year_string + " AND " + sql_ma + " AND " + sql_gcdp).count.to_f

    @info['ma_ogip_this_month'] = ActiveRecord::Base.connection.execute("SELECT expa_applications.* FROM expa_applications INNER JOIN expa_people ON expa_applications.xp_person_id = expa_people.xp_id INNER JOIN expa_opportunities ON expa_applications.xp_opportunity_id = expa_opportunities.id WHERE " + sql_lc_query + " AND (expa_applications.xp_updated_at BETWEEN " + this_month_string + " AND " + sql_ma + " AND " + sql_gip).count.to_f
    @info['ma_ogip_past_month'] = ActiveRecord::Base.connection.execute("SELECT expa_applications.* FROM expa_applications INNER JOIN expa_people ON expa_applications.xp_person_id = expa_people.xp_id INNER JOIN expa_opportunities ON expa_applications.xp_opportunity_id = expa_opportunities.id WHERE " + sql_lc_query + " AND (expa_applications.xp_updated_at BETWEEN " + past_month_string + " AND " + sql_ma + " AND " + sql_gip).count.to_f
    @info['ma_ogip_past_year'] = ActiveRecord::Base.connection.execute("SELECT expa_applications.* FROM expa_applications INNER JOIN expa_people ON expa_applications.xp_person_id = expa_people.xp_id INNER JOIN expa_opportunities ON expa_applications.xp_opportunity_id = expa_opportunities.id WHERE " + sql_lc_query + " AND (expa_applications.xp_updated_at BETWEEN " + this_month_past_year_string + " AND " + sql_ma + " AND " + sql_gip).count.to_f

    @info['re_ogcdp_this_month'] = ActiveRecord::Base.connection.execute("SELECT expa_applications.* FROM expa_applications INNER JOIN expa_people ON expa_applications.xp_person_id = expa_people.xp_id INNER JOIN expa_opportunities ON expa_applications.xp_opportunity_id = expa_opportunities.id WHERE " + sql_lc_query + " AND (expa_applications.xp_updated_at BETWEEN " + this_month_string + " AND " + sql_re + " AND " + sql_gcdp).count.to_f
    @info['re_ogcdp_past_month'] = ActiveRecord::Base.connection.execute("SELECT expa_applications.* FROM expa_applications INNER JOIN expa_people ON expa_applications.xp_person_id = expa_people.xp_id INNER JOIN expa_opportunities ON expa_applications.xp_opportunity_id = expa_opportunities.id WHERE " + sql_lc_query + " AND (expa_applications.xp_updated_at BETWEEN " + past_month_string + " AND " + sql_re + " AND " + sql_gcdp).count.to_f
    @info['re_ogcdp_past_year'] = ActiveRecord::Base.connection.execute("SELECT expa_applications.* FROM expa_applications INNER JOIN expa_people ON expa_applications.xp_person_id = expa_people.xp_id INNER JOIN expa_opportunities ON expa_applications.xp_opportunity_id = expa_opportunities.id WHERE " + sql_lc_query + " AND (expa_applications.xp_updated_at BETWEEN " + this_month_past_year_string + " AND " + sql_re + " AND " + sql_gcdp).count.to_f

    @info['re_ogip_this_month'] = ActiveRecord::Base.connection.execute("SELECT expa_applications.* FROM expa_applications INNER JOIN expa_people ON expa_applications.xp_person_id = expa_people.xp_id INNER JOIN expa_opportunities ON expa_applications.xp_opportunity_id = expa_opportunities.id WHERE " + sql_lc_query + " AND (expa_applications.xp_updated_at BETWEEN " + this_month_string + " AND " + sql_re + " AND " + sql_gip).count.to_f
    @info['re_ogip_past_month'] = ActiveRecord::Base.connection.execute("SELECT expa_applications.* FROM expa_applications INNER JOIN expa_people ON expa_applications.xp_person_id = expa_people.xp_id INNER JOIN expa_opportunities ON expa_applications.xp_opportunity_id = expa_opportunities.id WHERE " + sql_lc_query + " AND (expa_applications.xp_updated_at BETWEEN " + past_month_string + " AND " + sql_re + " AND " + sql_gip).count.to_f
    @info['re_ogip_past_year'] = ActiveRecord::Base.connection.execute("SELECT expa_applications.* FROM expa_applications INNER JOIN expa_people ON expa_applications.xp_person_id = expa_people.xp_id INNER JOIN expa_opportunities ON expa_applications.xp_opportunity_id = expa_opportunities.id WHERE " + sql_lc_query + " AND (expa_applications.xp_updated_at BETWEEN " + this_month_past_year_string + " AND " + sql_re + " AND " + sql_gip).count.to_f

    @info['leads_this_month_per_week'] = ActiveRecord::Base.connection.execute("SELECT DATE_TRUNC('week', (expa_people.xp_created_at::timestamp)), COUNT (id) FROM expa_people WHERE " + sql_lc_query + " AND (expa_people.xp_created_at BETWEEN " + this_month_string + " GROUP BY 1 ORDER BY 1 ASC").values.map { |x,i| i.to_i }
    @info['leads_this_month_per_day'] = ActiveRecord::Base.connection.execute("SELECT DATE_TRUNC('day', (expa_people.xp_created_at::timestamp)), COUNT (id) FROM expa_people WHERE " + sql_lc_query + " AND (expa_people.xp_created_at BETWEEN " + this_month_string + " GROUP BY 1 ORDER BY 1 ASC").values.map { |x,i| i.to_i }

    @info['ip_ogcdp_this_month_per_week'] = ActiveRecord::Base.connection.execute("SELECT DATE_TRUNC('week', (expa_people.xp_created_at::timestamp)), COUNT (expa_people.id) FROM expa_people INNER JOIN expa_applications ON expa_applications.xp_person_id = expa_people.xp_id INNER JOIN expa_opportunities ON expa_applications.xp_opportunity_id = expa_opportunities.id WHERE expa_people.xp_status = 1 AND " + sql_lc_query + " AND (expa_people.xp_created_at BETWEEN " + this_month_string + " AND " + sql_gcdp + " GROUP BY 1 ORDER BY 1 ASC").values.map { |x,i| i.to_i }
    @info['ip_ogcdp_this_month_per_day'] = ActiveRecord::Base.connection.execute("SELECT DATE_TRUNC('day', (expa_people.xp_created_at::timestamp)), COUNT (expa_people.id) FROM expa_people INNER JOIN expa_applications ON expa_applications.xp_person_id = expa_people.xp_id INNER JOIN expa_opportunities ON expa_applications.xp_opportunity_id = expa_opportunities.id WHERE expa_people.xp_status = 1 AND " + sql_lc_query + " AND (expa_people.xp_created_at BETWEEN " + this_month_string + " AND " + sql_gcdp + " GROUP BY 1 ORDER BY 1 ASC").values.map { |x,i| i.to_i }
    @info['ip_ogip_this_month_per_week'] = ActiveRecord::Base.connection.execute("SELECT DATE_TRUNC('week', (expa_people.xp_created_at::timestamp)), COUNT (expa_people.id) FROM expa_people INNER JOIN expa_applications ON expa_applications.xp_person_id = expa_people.xp_id INNER JOIN expa_opportunities ON expa_applications.xp_opportunity_id = expa_opportunities.id WHERE expa_people.xp_status = 1 AND " + sql_lc_query + " AND (expa_people.xp_created_at BETWEEN " + this_month_string + " AND " + sql_gip + " GROUP BY 1 ORDER BY 1 ASC").values.map { |x,i| i.to_i }
    @info['ip_ogip_this_month_per_day'] = ActiveRecord::Base.connection.execute("SELECT DATE_TRUNC('day', (expa_people.xp_created_at::timestamp)), COUNT (expa_people.id) FROM expa_people INNER JOIN expa_applications ON expa_applications.xp_person_id = expa_people.xp_id INNER JOIN expa_opportunities ON expa_applications.xp_opportunity_id = expa_opportunities.id WHERE expa_people.xp_status = 1 AND " + sql_lc_query + " AND (expa_people.xp_created_at BETWEEN " + this_month_string + " AND " + sql_gip + " GROUP BY 1 ORDER BY 1 ASC").values.map { |x,i| i.to_i }

    @info['ma_this_month_per_week'] = ActiveRecord::Base.connection.execute("SELECT DATE_TRUNC('week', (expa_applications.xp_updated_at::timestamp)), COUNT (expa_applications.id) FROM expa_applications INNER JOIN expa_people ON expa_applications.xp_person_id = expa_people.xp_id INNER JOIN expa_opportunities ON expa_applications.xp_opportunity_id = expa_opportunities.id WHERE " + sql_lc_query + " AND (expa_applications.xp_updated_at BETWEEN " + this_month_string + " AND " + sql_ogx + " AND " + sql_ma + " GROUP BY 1 ORDER BY 1 ASC").values.map { |x,i| i.to_i }
    @info['ma_this_month_per_day'] = ActiveRecord::Base.connection.execute("SELECT DATE_TRUNC('day', (expa_applications.xp_updated_at::timestamp)), COUNT (expa_applications.id) FROM expa_applications INNER JOIN expa_people ON expa_applications.xp_person_id = expa_people.xp_id INNER JOIN expa_opportunities ON expa_applications.xp_opportunity_id = expa_opportunities.id WHERE " + sql_lc_query + " AND (expa_applications.xp_updated_at BETWEEN " + this_month_string + " AND " + sql_ogx + " AND " + sql_ma + " GROUP BY 1 ORDER BY 1 ASC").values.map { |x,i| i.to_i }
    @info['ma_ogcdp_this_month_per_week'] = ActiveRecord::Base.connection.execute("SELECT DATE_TRUNC('week', (expa_applications.xp_updated_at::timestamp)), COUNT (expa_applications.id) FROM expa_applications INNER JOIN expa_people ON expa_applications.xp_person_id = expa_people.xp_id INNER JOIN expa_opportunities ON expa_applications.xp_opportunity_id = expa_opportunities.id WHERE " + sql_lc_query + " AND (expa_applications.xp_updated_at BETWEEN " + this_month_string + " AND " + sql_gcdp + " AND " + sql_ma + " GROUP BY 1 ORDER BY 1 ASC").values.map { |x,i| i.to_i }
    @info['ma_ogcdp_this_month_per_day'] = ActiveRecord::Base.connection.execute("SELECT DATE_TRUNC('day', (expa_applications.xp_updated_at::timestamp)), COUNT (expa_applications.id) FROM expa_applications INNER JOIN expa_people ON expa_applications.xp_person_id = expa_people.xp_id INNER JOIN expa_opportunities ON expa_applications.xp_opportunity_id = expa_opportunities.id WHERE " + sql_lc_query + " AND (expa_applications.xp_updated_at BETWEEN " + this_month_string + " AND " + sql_gcdp + " AND " + sql_ma + " GROUP BY 1 ORDER BY 1 ASC").values.map { |x,i| i.to_i }
    @info['ma_ogip_this_month_per_week'] = ActiveRecord::Base.connection.execute("SELECT DATE_TRUNC('week', (expa_applications.xp_updated_at::timestamp)), COUNT (expa_applications.id) FROM expa_applications INNER JOIN expa_people ON expa_applications.xp_person_id = expa_people.xp_id INNER JOIN expa_opportunities ON expa_applications.xp_opportunity_id = expa_opportunities.id WHERE " + sql_lc_query + " AND (expa_applications.xp_updated_at BETWEEN " + this_month_string + " AND " + sql_gip + " AND " + sql_ma + " GROUP BY 1 ORDER BY 1 ASC").values.map { |x,i| i.to_i }
    @info['ma_ogip_this_month_per_day'] = ActiveRecord::Base.connection.execute("SELECT DATE_TRUNC('day', (expa_applications.xp_updated_at::timestamp)), COUNT (expa_applications.id) FROM expa_applications INNER JOIN expa_people ON expa_applications.xp_person_id = expa_people.xp_id INNER JOIN expa_opportunities ON expa_applications.xp_opportunity_id = expa_opportunities.id WHERE " + sql_lc_query + " AND (expa_applications.xp_updated_at BETWEEN " + this_month_string + " AND " + sql_gip + " AND " + sql_ma + " GROUP BY 1 ORDER BY 1 ASC").values.map { |x,i| i.to_i }

    @info['re_this_month_per_week'] = ActiveRecord::Base.connection.execute("SELECT DATE_TRUNC('week', (expa_applications.xp_updated_at::timestamp)), COUNT (expa_applications.id) FROM expa_applications INNER JOIN expa_people ON expa_applications.xp_person_id = expa_people.xp_id INNER JOIN expa_opportunities ON expa_applications.xp_opportunity_id = expa_opportunities.id WHERE " + sql_lc_query + " AND (expa_applications.xp_updated_at BETWEEN " + this_month_string + " AND " + sql_ogx + " AND " + sql_re + " GROUP BY 1 ORDER BY 1 ASC").values.map { |x,i| i.to_i }
    @info['re_this_month_per_day'] = ActiveRecord::Base.connection.execute("SELECT DATE_TRUNC('day', (expa_applications.xp_updated_at::timestamp)), COUNT (expa_applications.id) FROM expa_applications INNER JOIN expa_people ON expa_applications.xp_person_id = expa_people.xp_id INNER JOIN expa_opportunities ON expa_applications.xp_opportunity_id = expa_opportunities.id WHERE " + sql_lc_query + " AND (expa_applications.xp_updated_at BETWEEN " + this_month_string + " AND " + sql_ogx + " AND " + sql_re + " GROUP BY 1 ORDER BY 1 ASC").values.map { |x,i| i.to_i }
    @info['re_ogcdp_this_month_per_week'] = ActiveRecord::Base.connection.execute("SELECT DATE_TRUNC('week', (expa_applications.xp_updated_at::timestamp)), COUNT (expa_applications.id) FROM expa_applications INNER JOIN expa_people ON expa_applications.xp_person_id = expa_people.xp_id INNER JOIN expa_opportunities ON expa_applications.xp_opportunity_id = expa_opportunities.id WHERE " + sql_lc_query + " AND (expa_applications.xp_updated_at BETWEEN " + this_month_string + " AND " + sql_gcdp + " AND " + sql_re + " GROUP BY 1 ORDER BY 1 ASC").values.map { |x,i| i.to_i }
    @info['re_ogcdp_this_month_per_day'] = ActiveRecord::Base.connection.execute("SELECT DATE_TRUNC('day', (expa_applications.xp_updated_at::timestamp)), COUNT (expa_applications.id) FROM expa_applications INNER JOIN expa_people ON expa_applications.xp_person_id = expa_people.xp_id INNER JOIN expa_opportunities ON expa_applications.xp_opportunity_id = expa_opportunities.id WHERE " + sql_lc_query + " AND (expa_applications.xp_updated_at BETWEEN " + this_month_string + " AND " + sql_gcdp + " AND " + sql_re + " GROUP BY 1 ORDER BY 1 ASC").values.map { |x,i| i.to_i }
    @info['re_ogip_this_month_per_week'] = ActiveRecord::Base.connection.execute("SELECT DATE_TRUNC('week', (expa_applications.xp_updated_at::timestamp)), COUNT (expa_applications.id) FROM expa_applications INNER JOIN expa_people ON expa_applications.xp_person_id = expa_people.xp_id INNER JOIN expa_opportunities ON expa_applications.xp_opportunity_id = expa_opportunities.id WHERE " + sql_lc_query + " AND (expa_applications.xp_updated_at BETWEEN " + this_month_string + " AND " + sql_gip + " AND " + sql_re + " GROUP BY 1 ORDER BY 1 ASC").values.map { |x,i| i.to_i }
    @info['re_ogip_this_month_per_day'] = ActiveRecord::Base.connection.execute("SELECT DATE_TRUNC('day', (expa_applications.xp_updated_at::timestamp)), COUNT (expa_applications.id) FROM expa_applications INNER JOIN expa_people ON expa_applications.xp_person_id = expa_people.xp_id INNER JOIN expa_opportunities ON expa_applications.xp_opportunity_id = expa_opportunities.id WHERE " + sql_lc_query + " AND (expa_applications.xp_updated_at BETWEEN " + this_month_string + " AND " + sql_gip + " AND " + sql_re + " GROUP BY 1 ORDER BY 1 ASC").values.map { |x,i| i.to_i }

    @info['ma_total'] = ExpaApplicationDAO.number_of_ma(office, Time.new(1970, 1, 1)..Time.now)
    @info['re_total'] = ExpaApplicationDAO.number_of_re(office, Time.new(1970, 1, 1)..Time.now)

    @info['ma_ogcdp_total'] = ActiveRecord::Base.connection.execute("SELECT expa_people.* FROM expa_people INNER JOIN expa_applications ON expa_applications.xp_person_id = expa_people.xp_id INNER JOIN expa_opportunities ON expa_applications.xp_opportunity_id = expa_opportunities.id WHERE expa_people.xp_status = 2 AND " + sql_gcdp).count
    @info['re_ogcdp_total'] = ActiveRecord::Base.connection.execute("SELECT expa_people.* FROM expa_people INNER JOIN expa_applications ON expa_applications.xp_person_id = expa_people.xp_id INNER JOIN expa_opportunities ON expa_applications.xp_opportunity_id = expa_opportunities.id WHERE expa_people.xp_status = 3 AND " + sql_gcdp).count

    @info['ma_ogip_total'] = ActiveRecord::Base.connection.execute("SELECT expa_people.* FROM expa_people INNER JOIN expa_applications ON expa_applications.xp_person_id = expa_people.xp_id INNER JOIN expa_opportunities ON expa_applications.xp_opportunity_id = expa_opportunities.id WHERE expa_people.xp_status = 2 AND " + sql_gip).count
    @info['re_ogip_total'] = ActiveRecord::Base.connection.execute("SELECT expa_people.* FROM expa_people INNER JOIN expa_applications ON expa_applications.xp_person_id = expa_people.xp_id INNER JOIN expa_opportunities ON expa_applications.xp_opportunity_id = expa_opportunities.id WHERE expa_people.xp_status = 3 AND " + sql_gip).count

    @info['ma_arab'] = ActiveRecord::Base.connection.execute("SELECT expa_people.* FROM expa_people INNER JOIN expa_applications ON expa_applications.xp_person_id = expa_people.xp_id INNER JOIN expa_opportunities ON expa_applications.xp_opportunity_id = expa_opportunities.id WHERE " + sql_ma + " AND " + sql_gcdp + "AND expa_people.interested_sub_product = 0").count
    @info['ma_east_europe'] = ActiveRecord::Base.connection.execute("SELECT expa_people.* FROM expa_people INNER JOIN expa_applications ON expa_applications.xp_person_id = expa_people.xp_id INNER JOIN expa_opportunities ON expa_applications.xp_opportunity_id = expa_opportunities.id WHERE " + sql_ma + " AND " + sql_gcdp + "AND expa_people.interested_sub_product = 1").count
    @info['ma_africa'] = ActiveRecord::Base.connection.execute("SELECT expa_people.* FROM expa_people INNER JOIN expa_applications ON expa_applications.xp_person_id = expa_people.xp_id INNER JOIN expa_opportunities ON expa_applications.xp_opportunity_id = expa_opportunities.id WHERE " + sql_ma + " AND " + sql_gcdp + "AND expa_people.interested_sub_product = 2").count
    @info['ma_asia'] = ActiveRecord::Base.connection.execute("SELECT expa_people.* FROM expa_people INNER JOIN expa_applications ON expa_applications.xp_person_id = expa_people.xp_id INNER JOIN expa_opportunities ON expa_applications.xp_opportunity_id = expa_opportunities.id WHERE " + sql_ma + " AND " + sql_gcdp + "AND expa_people.interested_sub_product = 3").count
    @info['ma_latam'] = ActiveRecord::Base.connection.execute("SELECT expa_people.* FROM expa_people INNER JOIN expa_applications ON expa_applications.xp_person_id = expa_people.xp_id INNER JOIN expa_opportunities ON expa_applications.xp_opportunity_id = expa_opportunities.id WHERE " + sql_ma + " AND " + sql_gcdp + "AND expa_people.interested_sub_product = 4").count
    @info['ma_start_up'] = ActiveRecord::Base.connection.execute("SELECT expa_people.* FROM expa_people INNER JOIN expa_applications ON expa_applications.xp_person_id = expa_people.xp_id INNER JOIN expa_opportunities ON expa_applications.xp_opportunity_id = expa_opportunities.id WHERE " + sql_ma + " AND " + sql_gcdp + "AND expa_people.interested_sub_product = 5").count
    @info['ma_educacional'] = ActiveRecord::Base.connection.execute("SELECT expa_people.* FROM expa_people INNER JOIN expa_applications ON expa_applications.xp_person_id = expa_people.xp_id INNER JOIN expa_opportunities ON expa_applications.xp_opportunity_id = expa_opportunities.id WHERE " + sql_ma + " AND " + sql_gcdp + "AND expa_people.interested_sub_product = 6").count
    @info['ma_it'] = ActiveRecord::Base.connection.execute("SELECT expa_people.* FROM expa_people INNER JOIN expa_applications ON expa_applications.xp_person_id = expa_people.xp_id INNER JOIN expa_opportunities ON expa_applications.xp_opportunity_id = expa_opportunities.id WHERE " + sql_ma + " AND " + sql_gcdp + "AND expa_people.interested_sub_product = 7").count
    @info['ma_management'] = ActiveRecord::Base.connection.execute("SELECT expa_people.* FROM expa_people INNER JOIN expa_applications ON expa_applications.xp_person_id = expa_people.xp_id INNER JOIN expa_opportunities ON expa_applications.xp_opportunity_id = expa_opportunities.id WHERE " + sql_ma + " AND " + sql_gcdp + "AND expa_people.interested_sub_product = 8").count\

    @info['re_arab'] = ActiveRecord::Base.connection.execute("SELECT expa_people.* FROM expa_people INNER JOIN expa_applications ON expa_applications.xp_person_id = expa_people.xp_id INNER JOIN expa_opportunities ON expa_applications.xp_opportunity_id = expa_opportunities.id WHERE " + sql_re + " AND " + sql_gcdp + "AND expa_people.interested_sub_product = 0").count
    @info['re_east_europe'] = ActiveRecord::Base.connection.execute("SELECT expa_people.* FROM expa_people INNER JOIN expa_applications ON expa_applications.xp_person_id = expa_people.xp_id INNER JOIN expa_opportunities ON expa_applications.xp_opportunity_id = expa_opportunities.id WHERE " + sql_re + " AND " + sql_gcdp + "AND expa_people.interested_sub_product = 1").count
    @info['re_africa'] = ActiveRecord::Base.connection.execute("SELECT expa_people.* FROM expa_people INNER JOIN expa_applications ON expa_applications.xp_person_id = expa_people.xp_id INNER JOIN expa_opportunities ON expa_applications.xp_opportunity_id = expa_opportunities.id WHERE " + sql_re + " AND " + sql_gcdp + "AND expa_people.interested_sub_product = 2").count
    @info['re_asia'] = ActiveRecord::Base.connection.execute("SELECT expa_people.* FROM expa_people INNER JOIN expa_applications ON expa_applications.xp_person_id = expa_people.xp_id INNER JOIN expa_opportunities ON expa_applications.xp_opportunity_id = expa_opportunities.id WHERE " + sql_re + " AND " + sql_gcdp + "AND expa_people.interested_sub_product = 3").count
    @info['re_latam'] = ActiveRecord::Base.connection.execute("SELECT expa_people.* FROM expa_people INNER JOIN expa_applications ON expa_applications.xp_person_id = expa_people.xp_id INNER JOIN expa_opportunities ON expa_applications.xp_opportunity_id = expa_opportunities.id WHERE " + sql_re + " AND " + sql_gcdp + "AND expa_people.interested_sub_product = 4").count
    @info['re_start_up'] = ActiveRecord::Base.connection.execute("SELECT expa_people.* FROM expa_people INNER JOIN expa_applications ON expa_applications.xp_person_id = expa_people.xp_id INNER JOIN expa_opportunities ON expa_applications.xp_opportunity_id = expa_opportunities.id WHERE " + sql_re + " AND " + sql_gcdp + "AND expa_people.interested_sub_product = 5").count
    @info['re_educacional'] = ActiveRecord::Base.connection.execute("SELECT expa_people.* FROM expa_people INNER JOIN expa_applications ON expa_applications.xp_person_id = expa_people.xp_id INNER JOIN expa_opportunities ON expa_applications.xp_opportunity_id = expa_opportunities.id WHERE " + sql_re + " AND " + sql_gcdp + "AND expa_people.interested_sub_product = 6").count
    @info['re_it'] = ActiveRecord::Base.connection.execute("SELECT expa_people.* FROM expa_people INNER JOIN expa_applications ON expa_applications.xp_person_id = expa_people.xp_id INNER JOIN expa_opportunities ON expa_applications.xp_opportunity_id = expa_opportunities.id WHERE " + sql_re + " AND " + sql_gcdp + "AND expa_people.interested_sub_product = 7").count
    @info['re_management'] = ActiveRecord::Base.connection.execute("SELECT expa_people.* FROM expa_people INNER JOIN expa_applications ON expa_applications.xp_person_id = expa_people.xp_id INNER JOIN expa_opportunities ON expa_applications.xp_opportunity_id = expa_opportunities.id WHERE " + sql_re + " AND " + sql_gcdp + "AND expa_people.interested_sub_product = 8").count


    @info['leads_this_year_per_month'] = ActiveRecord::Base.connection.execute("SELECT DATE_TRUNC('month', (expa_people.xp_created_at::timestamp)), COUNT (expa_people.id) FROM expa_people WHERE " + sql_lc_query + " AND (expa_people.xp_created_at BETWEEN " + this_year_string + " GROUP BY 1 ORDER BY 1 ASC").values.map { |x,i| [i] }.each_with_index.map { |x,i| [i+1,x.first.to_i] }
    @info['ma_this_year_per_month'] = ActiveRecord::Base.connection.execute("SELECT DATE_TRUNC('month', (expa_people.xp_created_at::timestamp)), COUNT (expa_people.id) FROM expa_people INNER JOIN expa_applications ON expa_applications.xp_person_id = expa_people.xp_id INNER JOIN expa_opportunities ON expa_applications.xp_opportunity_id = expa_opportunities.id WHERE " + sql_lc_query + " AND (expa_people.xp_created_at BETWEEN " + this_year_string + " AND " + sql_ogx + " AND " + sql_ma + " GROUP BY 1 ORDER BY 1 ASC").values.map { |x,i| [i] }.each_with_index.map { |x,i| [i+1,x.first.to_i] }
    @info['ma_ogcdp_this_year_per_month'] = ActiveRecord::Base.connection.execute("SELECT DATE_TRUNC('month', (expa_people.xp_created_at::timestamp)), COUNT (expa_people.id) FROM expa_people INNER JOIN expa_applications ON expa_applications.xp_person_id = expa_people.xp_id INNER JOIN expa_opportunities ON expa_applications.xp_opportunity_id = expa_opportunities.id WHERE " + sql_lc_query + " AND (expa_people.xp_created_at BETWEEN " + this_year_string + " AND " + sql_gcdp + " AND " + sql_ma + " GROUP BY 1 ORDER BY 1 ASC").values.map { |x,i| [i] }.each_with_index.map { |x,i| [i+1,x.first.to_i] }
    @info['ma_ogip_this_year_per_month'] = ActiveRecord::Base.connection.execute("SELECT DATE_TRUNC('month', (expa_people.xp_created_at::timestamp)), COUNT (expa_people.id) FROM expa_people INNER JOIN expa_applications ON expa_applications.xp_person_id = expa_people.xp_id INNER JOIN expa_opportunities ON expa_applications.xp_opportunity_id = expa_opportunities.id WHERE " + sql_lc_query + " AND (expa_people.xp_created_at BETWEEN " + this_year_string + " AND " + sql_gip + " AND " + sql_ma + " GROUP BY 1 ORDER BY 1 ASC").values.map { |x,i| [i] }.each_with_index.map { |x,i| [i+1,x.first.to_i] }
    @info['re_this_year_per_month'] = ActiveRecord::Base.connection.execute("SELECT DATE_TRUNC('month', (expa_people.xp_created_at::timestamp)), COUNT (expa_people.id) FROM expa_people INNER JOIN expa_applications ON expa_applications.xp_person_id = expa_people.xp_id INNER JOIN expa_opportunities ON expa_applications.xp_opportunity_id = expa_opportunities.id WHERE " + sql_lc_query + " AND (expa_people.xp_created_at BETWEEN " + this_year_string + " AND " + sql_ogx + " AND " + sql_re + " GROUP BY 1 ORDER BY 1 ASC").values.map { |x,i| [i] }.each_with_index.map { |x,i| [i+1,x.first.to_i] }
    @info['re_ogcdp_this_year_per_month'] = ActiveRecord::Base.connection.execute("SELECT DATE_TRUNC('month', (expa_people.xp_created_at::timestamp)), COUNT (expa_people.id) FROM expa_people INNER JOIN expa_applications ON expa_applications.xp_person_id = expa_people.xp_id INNER JOIN expa_opportunities ON expa_applications.xp_opportunity_id = expa_opportunities.id WHERE " + sql_lc_query + " AND (expa_people.xp_created_at BETWEEN " + this_year_string + " AND " + sql_gcdp + " AND " + sql_re + " GROUP BY 1 ORDER BY 1 ASC").values.map { |x,i| [i] }.each_with_index.map { |x,i| [i+1,x.first.to_i] }
    @info['re_ogip_this_year_per_month'] = ActiveRecord::Base.connection.execute("SELECT DATE_TRUNC('month', (expa_people.xp_created_at::timestamp)), COUNT (expa_people.id) FROM expa_people INNER JOIN expa_applications ON expa_applications.xp_person_id = expa_people.xp_id INNER JOIN expa_opportunities ON expa_applications.xp_opportunity_id = expa_opportunities.id WHERE " + sql_lc_query + " AND (expa_people.xp_created_at BETWEEN " + this_year_string + " AND " + sql_gip + " AND " + sql_re + " GROUP BY 1 ORDER BY 1 ASC").values.map { |x,i| [i] }.each_with_index.map { |x,i| [i+1,x.first.to_i] }

    @info['leads_last_year_per_month'] = ActiveRecord::Base.connection.execute("SELECT DATE_TRUNC('month', (expa_people.xp_created_at::timestamp)), COUNT (expa_people.id) FROM expa_people WHERE " + sql_lc_query + " AND (expa_people.xp_created_at BETWEEN " + past_year_string + " GROUP BY 1 ORDER BY 1 ASC").values.map { |x,i| [i] }.each_with_index.map { |x,i| [i+1,x.first.to_i] }
    @info['ma_last_year_per_month'] = ActiveRecord::Base.connection.execute("SELECT DATE_TRUNC('month', (expa_people.xp_created_at::timestamp)), COUNT (expa_people.id) FROM expa_people INNER JOIN expa_applications ON expa_applications.xp_person_id = expa_people.xp_id INNER JOIN expa_opportunities ON expa_applications.xp_opportunity_id = expa_opportunities.id WHERE " + sql_lc_query + " AND (expa_people.xp_created_at BETWEEN " + past_year_string + " AND " + sql_ogx + " AND " + sql_ma + " GROUP BY 1 ORDER BY 1 ASC").values.map { |x,i| [i] }.each_with_index.map { |x,i| [i+1,x.first.to_i] }
    @info['ma_ogcdp_last_year_per_month'] = ActiveRecord::Base.connection.execute("SELECT DATE_TRUNC('month', (expa_people.xp_created_at::timestamp)), COUNT (expa_people.id) FROM expa_people INNER JOIN expa_applications ON expa_applications.xp_person_id = expa_people.xp_id INNER JOIN expa_opportunities ON expa_applications.xp_opportunity_id = expa_opportunities.id WHERE " + sql_lc_query + " AND (expa_people.xp_created_at BETWEEN " + past_year_string + " AND " + sql_gcdp + " AND " + sql_ma + " GROUP BY 1 ORDER BY 1 ASC").values.map { |x,i| [i] }.each_with_index.map { |x,i| [i+1,x.first.to_i] }
    @info['ma_ogip_last_year_per_month'] = ActiveRecord::Base.connection.execute("SELECT DATE_TRUNC('month', (expa_people.xp_created_at::timestamp)), COUNT (expa_people.id) FROM expa_people INNER JOIN expa_applications ON expa_applications.xp_person_id = expa_people.xp_id INNER JOIN expa_opportunities ON expa_applications.xp_opportunity_id = expa_opportunities.id WHERE " + sql_lc_query + " AND (expa_people.xp_created_at BETWEEN " + past_year_string + " AND " + sql_gip + " AND " + sql_ma + " GROUP BY 1 ORDER BY 1 ASC").values.map { |x,i| [i] }.each_with_index.map { |x,i| [i+1,x.first.to_i] }
    @info['re_last_year_per_month'] = ActiveRecord::Base.connection.execute("SELECT DATE_TRUNC('month', (expa_people.xp_created_at::timestamp)), COUNT (expa_people.id) FROM expa_people INNER JOIN expa_applications ON expa_applications.xp_person_id = expa_people.xp_id INNER JOIN expa_opportunities ON expa_applications.xp_opportunity_id = expa_opportunities.id WHERE " + sql_lc_query + " AND (expa_people.xp_created_at BETWEEN " + past_year_string + " AND " + sql_ogx + " AND " + sql_re + " GROUP BY 1 ORDER BY 1 ASC").values.map { |x,i| [i] }.each_with_index.map { |x,i| [i+1,x.first.to_i] }
    @info['re_ogcdp_last_year_per_month'] = ActiveRecord::Base.connection.execute("SELECT DATE_TRUNC('month', (expa_people.xp_created_at::timestamp)), COUNT (expa_people.id) FROM expa_people INNER JOIN expa_applications ON expa_applications.xp_person_id = expa_people.xp_id INNER JOIN expa_opportunities ON expa_applications.xp_opportunity_id = expa_opportunities.id WHERE " + sql_lc_query + " AND (expa_people.xp_created_at BETWEEN " + past_year_string + " AND " + sql_gcdp + " AND " + sql_re + " GROUP BY 1 ORDER BY 1 ASC").values.map { |x,i| [i] }.each_with_index.map { |x,i| [i+1,x.first.to_i] }
    @info['re_ogip_last_year_per_month'] = ActiveRecord::Base.connection.execute("SELECT DATE_TRUNC('month', (expa_people.xp_created_at::timestamp)), COUNT (expa_people.id) FROM expa_people INNER JOIN expa_applications ON expa_applications.xp_person_id = expa_people.xp_id INNER JOIN expa_opportunities ON expa_applications.xp_opportunity_id = expa_opportunities.id WHERE " + sql_lc_query + " AND (expa_people.xp_created_at BETWEEN " + past_year_string + " AND " + sql_gip + " AND " + sql_re + " GROUP BY 1 ORDER BY 1 ASC").values.map { |x,i| [i] }.each_with_index.map { |x,i| [i+1,x.first.to_i] }

    @info['get_to_know_aiesec_total'] = ActiveRecord::Base.connection.execute("SELECT how_got_to_know_aiesec, COUNT(how_got_to_know_aiesec) FROM expa_people WHERE " + sql_lc_query + " GROUP BY how_got_to_know_aiesec").to_a.map { |x,i| x.to_a.map { |x,i| (i.nil? ? nil : x=='how_got_to_know_aiesec' ? DigitalTransformation.how_got_to_know_aiesec[i.to_i + 1] : i.to_i) } }.select { |x| !x.include?(nil) }
    @info['get_to_know_aiesec_this_month'] = ActiveRecord::Base.connection.execute("SELECT how_got_to_know_aiesec, COUNT(how_got_to_know_aiesec) FROM expa_people WHERE " + sql_lc_query + " AND (expa_people.xp_created_at BETWEEN " + this_month_string + " GROUP BY how_got_to_know_aiesec").to_a.map { |x,i| x.to_a.map { |x,i| (i.nil? ? nil : x=='how_got_to_know_aiesec' ? DigitalTransformation.how_got_to_know_aiesec[i.to_i + 1] : i.to_i) } }.select { |x| !x.include?(nil) }
    @info['get_to_know_aiesec_past_month'] = ActiveRecord::Base.connection.execute("SELECT how_got_to_know_aiesec, COUNT(how_got_to_know_aiesec) FROM expa_people WHERE " + sql_lc_query + " AND (expa_people.xp_created_at BETWEEN " + past_month_string + " GROUP BY how_got_to_know_aiesec").to_a.map { |x,i| x.to_a.map { |x,i| (i.nil? ? nil : x=='how_got_to_know_aiesec' ? DigitalTransformation.how_got_to_know_aiesec[i.to_i + 1] : i.to_i) } }.select { |x| !x.include?(nil) }

    @info['get_to_know_aiesec_gcdp_total'] = ActiveRecord::Base.connection.execute("SELECT how_got_to_know_aiesec, COUNT(how_got_to_know_aiesec) FROM expa_people INNER JOIN expa_applications ON expa_applications.xp_person_id = expa_people.xp_id INNER JOIN expa_opportunities ON expa_applications.xp_opportunity_id = expa_opportunities.id WHERE " + sql_lc_query + " AND " + sql_gcdp + "  GROUP BY how_got_to_know_aiesec").to_a.map { |x,i| x.to_a.map { |x,i| (i.nil? ? nil : x=='how_got_to_know_aiesec' ? DigitalTransformation.how_got_to_know_aiesec[i.to_i + 1] : i.to_i) } }.select { |x| !x.include?(nil) }
    @info['get_to_know_aiesec_gcdp_this_month'] = ActiveRecord::Base.connection.execute("SELECT how_got_to_know_aiesec, COUNT(how_got_to_know_aiesec) FROM expa_people INNER JOIN expa_applications ON expa_applications.xp_person_id = expa_people.xp_id INNER JOIN expa_opportunities ON expa_applications.xp_opportunity_id = expa_opportunities.id WHERE " + sql_lc_query + " AND " + sql_gcdp + " AND (expa_people.xp_created_at BETWEEN " + this_month_string + " GROUP BY how_got_to_know_aiesec").to_a.map { |x,i| x.to_a.map { |x,i| (i.nil? ? nil : x=='how_got_to_know_aiesec' ? DigitalTransformation.how_got_to_know_aiesec[i.to_i + 1] : i.to_i) } }.select { |x| !x.include?(nil) }
    @info['get_to_know_aiesec_gcdp_past_month'] = ActiveRecord::Base.connection.execute("SELECT how_got_to_know_aiesec, COUNT(how_got_to_know_aiesec) FROM expa_people INNER JOIN expa_applications ON expa_applications.xp_person_id = expa_people.xp_id INNER JOIN expa_opportunities ON expa_applications.xp_opportunity_id = expa_opportunities.id WHERE " + sql_lc_query + " AND " + sql_gcdp + " AND (expa_people.xp_created_at BETWEEN " + past_month_string + " GROUP BY how_got_to_know_aiesec").to_a.map { |x,i| x.to_a.map { |x,i| (i.nil? ? nil : x=='how_got_to_know_aiesec' ? DigitalTransformation.how_got_to_know_aiesec[i.to_i + 1] : i.to_i) } }.select { |x| !x.include?(nil) }

    @info['get_to_know_aiesec_gip_total'] = ActiveRecord::Base.connection.execute("SELECT how_got_to_know_aiesec, COUNT(how_got_to_know_aiesec) FROM expa_people INNER JOIN expa_applications ON expa_applications.xp_person_id = expa_people.xp_id INNER JOIN expa_opportunities ON expa_applications.xp_opportunity_id = expa_opportunities.id WHERE " + sql_lc_query + " AND " + sql_gip + " GROUP BY how_got_to_know_aiesec").to_a.map { |x,i| x.to_a.map { |x,i| (i.nil? ? nil : x=='how_got_to_know_aiesec' ? DigitalTransformation.how_got_to_know_aiesec[i.to_i + 1] : i.to_i) } }.select { |x| !x.include?(nil) }
    @info['get_to_know_aiesec_gip_this_month'] = ActiveRecord::Base.connection.execute("SELECT how_got_to_know_aiesec, COUNT(how_got_to_know_aiesec) FROM expa_people INNER JOIN expa_applications ON expa_applications.xp_person_id = expa_people.xp_id INNER JOIN expa_opportunities ON expa_applications.xp_opportunity_id = expa_opportunities.id WHERE " + sql_lc_query + " AND " + sql_gip + " AND (expa_people.xp_created_at BETWEEN " + this_month_string + " GROUP BY how_got_to_know_aiesec").to_a.map { |x,i| x.to_a.map { |x,i| (i.nil? ? nil : x=='how_got_to_know_aiesec' ? DigitalTransformation.how_got_to_know_aiesec[i.to_i + 1] : i.to_i) } }.select { |x| !x.include?(nil) }
    @info['get_to_know_aiesec_gip_past_month'] = ActiveRecord::Base.connection.execute("SELECT how_got_to_know_aiesec, COUNT(how_got_to_know_aiesec) FROM expa_people INNER JOIN expa_applications ON expa_applications.xp_person_id = expa_people.xp_id INNER JOIN expa_opportunities ON expa_applications.xp_opportunity_id = expa_opportunities.id WHERE " + sql_lc_query + " AND " + sql_gip + " AND (expa_people.xp_created_at BETWEEN " + past_month_string + " GROUP BY how_got_to_know_aiesec").to_a.map { |x,i| x.to_a.map { |x,i| (i.nil? ? nil : x=='how_got_to_know_aiesec' ? DigitalTransformation.how_got_to_know_aiesec[i.to_i + 1] : i.to_i) } }.select { |x| !x.include?(nil) }

    @info['average_number_of_applications_total'] = ActiveRecord::Base.connection.execute("SELECT AVG(count) FROM (SELECT COUNT(*) FROM expa_applications INNER JOIN expa_people ON expa_applications.xp_person_id = expa_people.xp_id WHERE " + sql_lc_query + " GROUP BY xp_person_id) as counts").to_a.first['avg'].to_f
    @info['average_number_of_applications_this_month'] = ActiveRecord::Base.connection.execute("SELECT AVG(count) FROM (SELECT COUNT(*) FROM expa_applications INNER JOIN expa_people ON expa_applications.xp_person_id = expa_people.xp_id WHERE " + sql_lc_query + " AND (expa_people.xp_created_at BETWEEN " + this_month_string + " GROUP BY xp_person_id) as counts").to_a.first['avg'].to_f
    @info['average_number_of_applications_past_month'] = ActiveRecord::Base.connection.execute("SELECT AVG(count) FROM (SELECT COUNT(*) FROM expa_applications INNER JOIN expa_people ON expa_applications.xp_person_id = expa_people.xp_id WHERE " + sql_lc_query + " AND (expa_people.xp_created_at BETWEEN " + past_month_string + " GROUP BY xp_person_id) as counts").to_a.first['avg'].to_f

    @info['average_conversion_time_ma_total'] = ActiveRecord::Base.connection.execute("SELECT AVG(expa_applications.xp_date_matched-expa_people.xp_created_at) FROM expa_applications INNER JOIN expa_people on expa_applications.xp_person_id = expa_people.xp_id WHERE " + sql_lc_query + " AND " + sql_ma).to_a.first['avg']
    @info['average_conversion_time_ma_this_month'] = ActiveRecord::Base.connection.execute("SELECT AVG(expa_applications.xp_date_matched-expa_people.xp_created_at) FROM expa_applications INNER JOIN expa_people on expa_applications.xp_person_id = expa_people.xp_id WHERE " + sql_lc_query + " AND " + sql_ma + " AND (expa_people.xp_created_at BETWEEN " + this_month_string).to_a.first['avg']
    @info['average_conversion_time_ma_past_month'] = ActiveRecord::Base.connection.execute("SELECT AVG(expa_applications.xp_date_matched-expa_people.xp_created_at) FROM expa_applications INNER JOIN expa_people on expa_applications.xp_person_id = expa_people.xp_id WHERE " + sql_lc_query + " AND " + sql_ma + " AND (expa_people.xp_created_at BETWEEN " + past_month_string).to_a.first['avg']

    @info['average_conversion_time_re_total'] = ActiveRecord::Base.connection.execute("SELECT AVG(expa_applications.xp_date_matched-expa_people.xp_created_at) FROM expa_applications INNER JOIN expa_people on expa_applications.xp_person_id = expa_people.xp_id WHERE " + sql_lc_query + " AND " + sql_re).to_a.first['avg']
    @info['average_conversion_time_re_this_month'] = ActiveRecord::Base.connection.execute("SELECT AVG(expa_applications.xp_date_matched-expa_people.xp_created_at) FROM expa_applications INNER JOIN expa_people on expa_applications.xp_person_id = expa_people.xp_id WHERE " + sql_lc_query + " AND " + sql_re + " AND (expa_people.xp_created_at BETWEEN " + this_month_string).to_a.first['avg']
    @info['average_conversion_time_re_past_month'] = ActiveRecord::Base.connection.execute("SELECT AVG(expa_applications.xp_date_matched-expa_people.xp_created_at) FROM expa_applications INNER JOIN expa_people on expa_applications.xp_person_id = expa_people.xp_id WHERE " + sql_lc_query + " AND " + sql_re + " AND (expa_people.xp_created_at BETWEEN " + past_month_string).to_a.first['avg']

    @info['average_number_of_applications_gcdp_total'] = ActiveRecord::Base.connection.execute("SELECT AVG(count) FROM (SELECT COUNT(*) FROM expa_applications INNER JOIN expa_people ON expa_applications.xp_person_id = expa_people.xp_id INNER JOIN expa_opportunities ON expa_applications.xp_opportunity_id = expa_opportunities.id WHERE " + sql_lc_query + " AND " + sql_gcdp + " GROUP BY xp_person_id) as counts").to_a.first['avg'].to_f
    @info['average_number_of_applications_gcdp_this_month'] = ActiveRecord::Base.connection.execute("SELECT AVG(count) FROM (SELECT COUNT(*) FROM expa_applications INNER JOIN expa_people ON expa_applications.xp_person_id = expa_people.xp_id INNER JOIN expa_opportunities ON expa_applications.xp_opportunity_id = expa_opportunities.id WHERE " + sql_lc_query + " AND " + sql_gcdp + " AND (expa_people.xp_created_at BETWEEN " + this_month_string + " GROUP BY xp_person_id) as counts").to_a.first['avg'].to_f
    @info['average_number_of_applications_gcdp_past_month'] = ActiveRecord::Base.connection.execute("SELECT AVG(count) FROM (SELECT COUNT(*) FROM expa_applications INNER JOIN expa_people ON expa_applications.xp_person_id = expa_people.xp_id INNER JOIN expa_opportunities ON expa_applications.xp_opportunity_id = expa_opportunities.id WHERE " + sql_lc_query + " AND " + sql_gcdp + " AND (expa_people.xp_created_at BETWEEN " + past_month_string + " GROUP BY xp_person_id) as counts").to_a.first['avg'].to_f

    @info['average_conversion_time_ma_gcdp_total'] = ActiveRecord::Base.connection.execute("SELECT AVG(expa_applications.xp_date_matched-expa_people.xp_created_at) FROM expa_applications INNER JOIN expa_people on expa_applications.xp_person_id = expa_people.xp_id INNER JOIN expa_opportunities ON expa_applications.xp_opportunity_id = expa_opportunities.id WHERE " + sql_lc_query + " AND " + sql_gcdp + " AND " + sql_ma).to_a.first['avg']
    @info['average_conversion_time_ma_gcdp_this_month'] = ActiveRecord::Base.connection.execute("SELECT AVG(expa_applications.xp_date_matched-expa_people.xp_created_at) FROM expa_applications INNER JOIN expa_people on expa_applications.xp_person_id = expa_people.xp_id INNER JOIN expa_opportunities ON expa_applications.xp_opportunity_id = expa_opportunities.id WHERE " + sql_lc_query + " AND " + sql_gcdp + " AND " + sql_ma + " AND (expa_people.xp_created_at BETWEEN " + this_month_string).to_a.first['avg']
    @info['average_conversion_time_ma_gcdp_past_month'] = ActiveRecord::Base.connection.execute("SELECT AVG(expa_applications.xp_date_matched-expa_people.xp_created_at) FROM expa_applications INNER JOIN expa_people on expa_applications.xp_person_id = expa_people.xp_id INNER JOIN expa_opportunities ON expa_applications.xp_opportunity_id = expa_opportunities.id WHERE " + sql_lc_query + " AND " + sql_gcdp + " AND " + sql_ma + " AND (expa_people.xp_created_at BETWEEN " + past_month_string).to_a.first['avg']

    @info['average_conversion_time_re_gcdp_total'] = ActiveRecord::Base.connection.execute("SELECT AVG(expa_applications.xp_date_matched-expa_people.xp_created_at) FROM expa_applications INNER JOIN expa_people on expa_applications.xp_person_id = expa_people.xp_id INNER JOIN expa_opportunities ON expa_applications.xp_opportunity_id = expa_opportunities.id WHERE " + sql_lc_query + " AND " + sql_gcdp + " AND " + sql_re).to_a.first['avg']
    @info['average_conversion_time_re_gcdp_this_month'] = ActiveRecord::Base.connection.execute("SELECT AVG(expa_applications.xp_date_matched-expa_people.xp_created_at) FROM expa_applications INNER JOIN expa_people on expa_applications.xp_person_id = expa_people.xp_id INNER JOIN expa_opportunities ON expa_applications.xp_opportunity_id = expa_opportunities.id WHERE " + sql_lc_query + " AND " + sql_gcdp + " AND " + sql_re + " AND (expa_people.xp_created_at BETWEEN " + this_month_string).to_a.first['avg']
    @info['average_conversion_time_re_gcdp_past_month'] = ActiveRecord::Base.connection.execute("SELECT AVG(expa_applications.xp_date_matched-expa_people.xp_created_at) FROM expa_applications INNER JOIN expa_people on expa_applications.xp_person_id = expa_people.xp_id INNER JOIN expa_opportunities ON expa_applications.xp_opportunity_id = expa_opportunities.id WHERE " + sql_lc_query + " AND " + sql_gcdp + " AND " + sql_re + " AND (expa_people.xp_created_at BETWEEN " + past_month_string).to_a.first['avg']

    @info['average_number_of_applications_gip_total'] = ActiveRecord::Base.connection.execute("SELECT AVG(count) FROM (SELECT COUNT(*) FROM expa_applications INNER JOIN expa_people ON expa_applications.xp_person_id = expa_people.xp_id INNER JOIN expa_opportunities ON expa_applications.xp_opportunity_id = expa_opportunities.id WHERE " + sql_lc_query + " AND " + sql_gip + " GROUP BY xp_person_id) as counts").to_a.first['avg'].to_f
    @info['average_number_of_applications_gip_this_month'] = ActiveRecord::Base.connection.execute("SELECT AVG(count) FROM (SELECT COUNT(*) FROM expa_applications INNER JOIN expa_people ON expa_applications.xp_person_id = expa_people.xp_id INNER JOIN expa_opportunities ON expa_applications.xp_opportunity_id = expa_opportunities.id WHERE " + sql_lc_query + " AND " + sql_gip + " AND (expa_people.xp_created_at BETWEEN " + this_month_string + " GROUP BY xp_person_id) as counts").to_a.first['avg'].to_f
    @info['average_number_of_applications_gip_past_month'] = ActiveRecord::Base.connection.execute("SELECT AVG(count) FROM (SELECT COUNT(*) FROM expa_applications INNER JOIN expa_people ON expa_applications.xp_person_id = expa_people.xp_id INNER JOIN expa_opportunities ON expa_applications.xp_opportunity_id = expa_opportunities.id WHERE " + sql_lc_query + " AND " + sql_gip + " AND (expa_people.xp_created_at BETWEEN " + past_month_string + " GROUP BY xp_person_id) as counts").to_a.first['avg'].to_f

    @info['average_conversion_time_ma_gip_total'] = ActiveRecord::Base.connection.execute("SELECT AVG(expa_applications.xp_date_matched-expa_people.xp_created_at) FROM expa_applications INNER JOIN expa_people on expa_applications.xp_person_id = expa_people.xp_id INNER JOIN expa_opportunities ON expa_applications.xp_opportunity_id = expa_opportunities.id WHERE " + sql_lc_query + " AND " + sql_gip + " AND " + sql_ma).to_a.first['avg']
    @info['average_conversion_time_ma_gip_this_month'] = ActiveRecord::Base.connection.execute("SELECT AVG(expa_applications.xp_date_matched-expa_people.xp_created_at) FROM expa_applications INNER JOIN expa_people on expa_applications.xp_person_id = expa_people.xp_id INNER JOIN expa_opportunities ON expa_applications.xp_opportunity_id = expa_opportunities.id WHERE " + sql_lc_query + " AND " + sql_gip + " AND " + sql_ma + " AND (expa_people.xp_created_at BETWEEN " + this_month_string).to_a.first['avg']
    @info['average_conversion_time_ma_gip_past_month'] = ActiveRecord::Base.connection.execute("SELECT AVG(expa_applications.xp_date_matched-expa_people.xp_created_at) FROM expa_applications INNER JOIN expa_people on expa_applications.xp_person_id = expa_people.xp_id INNER JOIN expa_opportunities ON expa_applications.xp_opportunity_id = expa_opportunities.id WHERE " + sql_lc_query + " AND " + sql_gip + " AND " + sql_ma + " AND (expa_people.xp_created_at BETWEEN " + past_month_string).to_a.first['avg']

    @info['average_conversion_time_re_gip_total'] = ActiveRecord::Base.connection.execute("SELECT AVG(expa_applications.xp_date_matched-expa_people.xp_created_at) FROM expa_applications INNER JOIN expa_people on expa_applications.xp_person_id = expa_people.xp_id INNER JOIN expa_opportunities ON expa_applications.xp_opportunity_id = expa_opportunities.id WHERE " + sql_lc_query + " AND " + sql_gip + " AND " + sql_re).to_a.first['avg']
    @info['average_conversion_time_re_gip_this_month'] = ActiveRecord::Base.connection.execute("SELECT AVG(expa_applications.xp_date_matched-expa_people.xp_created_at) FROM expa_applications INNER JOIN expa_people on expa_applications.xp_person_id = expa_people.xp_id INNER JOIN expa_opportunities ON expa_applications.xp_opportunity_id = expa_opportunities.id WHERE " + sql_lc_query + " AND " + sql_gip + " AND " + sql_re + " AND (expa_people.xp_created_at BETWEEN " + this_month_string).to_a.first['avg']
    @info['average_conversion_time_re_gip_past_month'] = ActiveRecord::Base.connection.execute("SELECT AVG(expa_applications.xp_date_matched-expa_people.xp_created_at) FROM expa_applications INNER JOIN expa_people on expa_applications.xp_person_id = expa_people.xp_id INNER JOIN expa_opportunities ON expa_applications.xp_opportunity_id = expa_opportunities.id WHERE " + sql_lc_query + " AND " + sql_gip + " AND " + sql_re + " AND (expa_people.xp_created_at BETWEEN " + past_month_string).to_a.first['avg']

  end

  def filter_list_leads(search_lc_query, page, date_start, date_end)
    limit = 30
    @people = ExpaPerson.where(search_lc_query).where(xp_updated_at: date_start..date_end).order(xp_updated_at: :desc).limit(limit).offset(limit*page)
  end
end